-- Kindred App Supabase Schema
-- Run this in your Supabase SQL Editor

-- 1. PROFILES TABLE (extends auth.users)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  dob DATE,
  suburb TEXT,
  phone TEXT,
  avatar_url TEXT,
  points INTEGER DEFAULT 0,
  id_verified BOOLEAN DEFAULT FALSE,
  reliability_score INTEGER,
  completed_exchanges INTEGER DEFAULT 0,
  total_exchanges INTEGER DEFAULT 0,
  streak INTEGER DEFAULT 0,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  notification_push BOOLEAN DEFAULT TRUE,
  notification_email BOOLEAN DEFAULT TRUE,
  notification_matches BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Users can view all profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- 2. ITEMS TABLE
CREATE TABLE public.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('give', 'need')),
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  status TEXT DEFAULT 'listed' CHECK (status IN ('listed', 'matched', 'arranged', 'ready', 'completed', 'cancelled')),
  note TEXT,
  available_until TEXT,
  food_expiry DATE,
  is_large_item BOOLEAN DEFAULT FALSE,
  urgency TEXT CHECK (urgency IN ('whenever', 'soon', 'urgent')),
  offer_in_return TEXT,
  other_person_id UUID REFERENCES public.profiles(id),
  handover_type TEXT,
  drop_point TEXT,
  drop_time TEXT,
  suburb TEXT,
  match_expiry TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- Items policies
CREATE POLICY "Anyone can view items" ON public.items FOR SELECT USING (true);
CREATE POLICY "Users can insert own items" ON public.items FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own items" ON public.items FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own items" ON public.items FOR DELETE USING (auth.uid() = user_id);

-- 3. ITEM_PHOTOS TABLE
CREATE TABLE public.item_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT REFERENCES public.items(id) ON DELETE CASCADE,
  storage_path TEXT NOT NULL,
  public_url TEXT NOT NULL,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.item_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view item photos" ON public.item_photos FOR SELECT USING (true);
CREATE POLICY "Users can insert own item photos" ON public.item_photos FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.items WHERE id = item_id AND user_id = auth.uid()));
CREATE POLICY "Users can delete own item photos" ON public.item_photos FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.items WHERE id = item_id AND user_id = auth.uid()));

-- 4. MATCHES TABLE
CREATE TABLE public.matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT REFERENCES public.items(id) ON DELETE CASCADE,
  giver_id UUID REFERENCES public.profiles(id),
  receiver_id UUID REFERENCES public.profiles(id),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own matches" ON public.matches FOR SELECT
  USING (giver_id = auth.uid() OR receiver_id = auth.uid());
CREATE POLICY "Users can create matches" ON public.matches FOR INSERT
  WITH CHECK (giver_id = auth.uid() OR receiver_id = auth.uid());
CREATE POLICY "Users can update own matches" ON public.matches FOR UPDATE
  USING (giver_id = auth.uid() OR receiver_id = auth.uid());

-- 5. CONVERSATIONS TABLE
CREATE TABLE public.conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES public.matches(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  other_user_id UUID REFERENCES public.profiles(id),
  item_id BIGINT REFERENCES public.items(id),
  blocked_by UUID,
  last_message TEXT,
  last_message_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own conversations" ON public.conversations FOR SELECT
  USING (user_id = auth.uid() OR other_user_id = auth.uid());
CREATE POLICY "Users can insert conversations" ON public.conversations FOR INSERT
  WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users can update own conversations" ON public.conversations FOR UPDATE
  USING (user_id = auth.uid() OR other_user_id = auth.uid());

-- 6. MESSAGES TABLE
CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id UUID REFERENCES auth.users(id),
  content TEXT NOT NULL,
  scam_flagged BOOLEAN DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Messages policies
CREATE POLICY "Users can view own messages" ON public.messages FOR SELECT
  USING (sender_id = auth.uid() OR EXISTS (
    SELECT 1 FROM public.conversations c
    WHERE c.id = conversation_id AND (c.user_id = auth.uid() OR c.other_user_id = auth.uid())
  ));
CREATE POLICY "Users can insert own messages" ON public.messages FOR INSERT
  WITH CHECK (sender_id = auth.uid());
CREATE POLICY "Users can update own messages" ON public.messages FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM public.conversations c
    WHERE c.id = conversation_id AND (c.user_id = auth.uid() OR c.other_user_id = auth.uid())
  ));

-- 7. NOTIFICATIONS TABLE
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT,
  body TEXT,
  item_id BIGINT,
  match_id BIGINT,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own notifications" ON public.notifications FOR SELECT
  USING (user_id = auth.uid());
CREATE POLICY "Users can update own notifications" ON public.notifications FOR UPDATE
  USING (user_id = auth.uid());

-- 8. RELIABILITY TABLE (for reliability tracking)
CREATE TABLE public.reliability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  partner_id UUID REFERENCES public.profiles(id),
  completed BOOLEAN NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  tags TEXT[],
  no_show_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.reliability ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own reliability" ON public.reliability FOR SELECT
  USING (user_id = auth.uid() OR partner_id = auth.uid());
CREATE POLICY "Users can insert reliability" ON public.reliability FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- 9. REPORTS TABLE
CREATE TABLE public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  reported_user_id UUID REFERENCES public.profiles(id),
  category TEXT NOT NULL,
  details TEXT,
  item_id BIGINT,
  conversation_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert reports" ON public.reports FOR INSERT
  WITH CHECK (reporter_id = auth.uid());

-- 10. FUNCTIONS

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, created_at)
  VALUES (NEW.id, NEW.raw_user_meta_data->>'display_name', NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Function to update points
CREATE OR REPLACE FUNCTION public.award_points(user_uuid UUID, points_to_add INTEGER)
RETURNS VOID AS $$
BEGIN
  UPDATE public.profiles
  SET points = points + points_to_add,
      completed_exchanges = completed_exchanges + 1,
      total_exchanges = total_exchanges + 1,
      streak = streak + 1,
      updated_at = NOW()
  WHERE id = user_uuid;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 11. STORAGE BUCKETS (run in Supabase dashboard or via API)
-- CREATE BUCKET 'item-photos' with public access
-- CREATE BUCKET 'avatars' with public access

-- 12. MIGRATION HELPER
-- If you already have the old schema deployed, run this migration instead:
--
-- ALTER TABLE public.items RENAME COLUMN item TO title;
-- ALTER TABLE public.items ADD COLUMN IF NOT EXISTS suburb TEXT;
-- ALTER TABLE public.items DROP COLUMN IF EXISTS photos;
-- ALTER TABLE public.items ALTER COLUMN status SET DEFAULT 'listed';
-- ALTER TABLE public.items DROP CONSTRAINT IF EXISTS items_status_check;
-- ALTER TABLE public.items ADD CONSTRAINT items_status_check CHECK (status IN ('listed', 'matched', 'arranged', 'ready', 'completed', 'cancelled'));
--
-- ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS scam_flagged BOOLEAN DEFAULT FALSE;
-- ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;
-- ALTER TABLE public.messages DROP COLUMN IF EXISTS is_read;
--
-- ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS match_id BIGINT;
-- ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;
-- ALTER TABLE public.notifications DROP COLUMN IF EXISTS is_read;
--
-- ALTER TABLE public.conversations ADD COLUMN IF NOT EXISTS match_id BIGINT REFERENCES public.matches(id);
-- ALTER TABLE public.conversations ADD COLUMN IF NOT EXISTS blocked_by UUID;
--
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS notification_push BOOLEAN DEFAULT TRUE;
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS notification_email BOOLEAN DEFAULT TRUE;
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS notification_matches BOOLEAN DEFAULT TRUE;
