-- Exchange receipts: slim record of completed exchanges
CREATE TABLE IF NOT EXISTS public.exchange_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT,
  item_title TEXT NOT NULL,
  item_type TEXT NOT NULL CHECK (item_type IN ('give', 'need')),
  category TEXT,
  giver_id UUID REFERENCES auth.users(id),
  receiver_id UUID REFERENCES auth.users(id),
  giver_name TEXT,
  receiver_name TEXT,
  rating INTEGER,
  points_earned INTEGER DEFAULT 0,
  completed_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.exchange_receipts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own receipts" ON public.exchange_receipts FOR SELECT
  USING (giver_id = auth.uid() OR receiver_id = auth.uid());

CREATE POLICY "Authenticated users can insert receipts" ON public.exchange_receipts FOR INSERT
  TO authenticated WITH CHECK (true);
