-- Offer photos: photos attached to a match/offer (for need items, the offerer shows what they have)
CREATE TABLE IF NOT EXISTS public.offer_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES public.matches(id) ON DELETE CASCADE,
  storage_path TEXT NOT NULL,
  public_url TEXT NOT NULL,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.offer_photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view offer photos" ON public.offer_photos FOR SELECT USING (true);
CREATE POLICY "Users can insert offer photos for own matches" ON public.offer_photos FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.matches
    WHERE id = match_id AND (giver_id = auth.uid() OR receiver_id = auth.uid())
  ));
CREATE POLICY "Users can delete own offer photos" ON public.offer_photos FOR DELETE
  USING (EXISTS (
    SELECT 1 FROM public.matches
    WHERE id = match_id AND (giver_id = auth.uid() OR receiver_id = auth.uid())
  ));
